# Verify Exported ONNX Model in FINN

<font color="red">**Live FINN tutorial:** We recommend clicking **Cell -> Run All** when you start reading this notebook for "latency hiding".</font>

**Important: This notebook depends on the 1-train-mlp-with-brevitas notebook, because we are using the ONNX model that was exported there. So please make sure the needed .onnx file is generated before you run this notebook.**

**Also remember to 'close and halt' any other FINN notebooks, since Netron visualizations use the same port.**

In this notebook we will show how to import the network we trained in Brevitas and verify it in the FINN compiler. 
This verification process can actually be done at various stages in the compiler [as explained in this notebook](../bnn-pynq/tfc_end2end_verification.ipynb) but for this example we'll only consider the first step: verifying the exported high-level FINN-ONNX model.
Another goal of this notebook is to introduce you to the concept of *graph transformations* -- we'll be applying some transformations to the graph to make it executable for verification. 
Once this model is sucessfully verified, we'll generate an FPGA accelerator from it in the next notebook.

In [1]:
import onnx 
import torch 

**This is important -- always import onnx before torch**. This is a workaround for a [known bug](https://github.com/onnx/onnx/issues/2394).

## Outline
-------------
1. [Import model into FINN with ModelWrapper](#brevitas_import_visualization)
2. [Network preparations: Tidy-up transformations](#network_preparations)
3. [Load the dataset and Brevitas model](#load_dataset) 
4. [Compare FINN and Brevitas execution](#compare_brevitas)

# 1. Import model into FINN with ModelWrapper <a id="brevitas_import_visualization"></a>

Now that we have the model in .onnx format, we can work with it using FINN. To import it into FINN, we'll use the [`ModelWrapper`](https://finn.readthedocs.io/en/latest/source_code/finn.core.html#qonnx.core.modelwrapper.ModelWrapper). It is a wrapper around the ONNX model which provides several helper functions to make it easier to work with the model.

In [2]:
import os
from qonnx.core.modelwrapper import ModelWrapper

model_dir = os.environ['FINN_ROOT'] + "/notebooks/FINN_Brevitas"
ready_model_filename = model_dir + "/finn-brevitas-ready.onnx"
model_for_sim = ModelWrapper(ready_model_filename)

Let's have a look at some of the member functions exposed by `ModelWrapper` to see what kind of information we can extract from it.

In [3]:
dir(model_for_sim)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_model_proto',
 'analysis',
 'check_all_tensor_shapes_specified',
 'check_compatibility',
 'cleanup',
 'find_consumer',
 'find_consumers',
 'find_direct_predecessors',
 'find_direct_successors',
 'find_producer',
 'find_upstream',
 'fix_float64',
 'get_all_tensor_names',
 'get_finn_nodes',
 'get_initializer',
 'get_metadata_prop',
 'get_node_from_name',
 'get_node_index',
 'get_nodes_by_op_type',
 'get_non_finn_nodes',
 'get_tensor_datatype',
 'get_tensor_fanout',
 'get_tensor_layout',
 'get_tensor_shape',
 'get_tensor_sparsity',
 'get_tensor_valueinfo',
 'graph',
 'is_fork_node',
 'is_join_node',
 'make_empty_exec_conte

Many of these helper functions relate to extracting information about the structure and properties of the ONNX model. You can find out more about examining and manipulating ONNX models programmatically in [this tutorial](../../basics/0_how_to_work_with_onnx.ipynb), but we'll show a few basic functions here. For instance, we can extract the shape and datatype annotation for various tensors in the graph, as well as information related to the operation types associated with each node.

In [4]:
from qonnx.core.datatype import DataType

finnonnx_in_tensor_name = model_for_sim.graph.input[0].name
finnonnx_out_tensor_name = model_for_sim.graph.output[0].name
print("Input tensor name: %s" % finnonnx_in_tensor_name)
print("Output tensor name: %s" % finnonnx_out_tensor_name)
finnonnx_model_in_shape = model_for_sim.get_tensor_shape(finnonnx_in_tensor_name)
finnonnx_model_out_shape = model_for_sim.get_tensor_shape(finnonnx_out_tensor_name)
print("Input tensor shape: %s" % str(finnonnx_model_in_shape))
print("Output tensor shape: %s" % str(finnonnx_model_out_shape))
finnonnx_model_in_dt = model_for_sim.get_tensor_datatype(finnonnx_in_tensor_name)
finnonnx_model_out_dt = model_for_sim.get_tensor_datatype(finnonnx_out_tensor_name)
print("Input tensor datatype: %s" % str(finnonnx_model_in_dt.name))
print("Output tensor datatype: %s" % str(finnonnx_model_out_dt.name))
print("List of node operator types in the graph: ")
print([x.op_type for x in model_for_sim.graph.node])

Input tensor name: global_in
Output tensor name: global_out
Input tensor shape: [1, 3, 64, 64]
Output tensor shape: [1, 4]
Input tensor datatype: FLOAT32
Output tensor datatype: FLOAT32
List of node operator types in the graph: 
['Reshape', 'MatMul', 'Mul', 'Add', 'BatchNormalization', 'MultiThreshold', 'Mul', 'MatMul', 'Mul', 'Add', 'BatchNormalization', 'MultiThreshold', 'Mul', 'MatMul', 'Mul', 'Add', 'BatchNormalization', 'MultiThreshold', 'Mul', 'MatMul', 'Mul', 'Add']


Note that the output tensor is (as of yet) marked as a float32 value, even though we know the output is binary. This will be automatically inferred by the compiler in the next step when we run the `InferDataTypes` transformation.

# 2. Network preparation: Tidy-up transformations <a id="network_preparations"></a>

Before running the verification, we need to prepare our FINN-ONNX model. In particular, all the intermediate tensors need to have statically defined shapes. To do this, we apply some graph transformations to the model like a kind of "tidy-up" to make it easier to process. 

**Graph transformations in FINN.** The whole FINN compiler is built around the idea of transformations, which gradually transform the model into a synthesizable hardware description. Although FINN offers functionality that automatically calls a standard sequence of transformations (covered in the next notebook), you can also manually call individual transformations (like we do here), as well as adding your own transformations, to create custom flows. You can read more about these transformations in [this notebook](../bnn-pynq/tfc_end2end_example.ipynb).

In [5]:
from qonnx.transformation.general import GiveReadableTensorNames, GiveUniqueNodeNames, RemoveStaticGraphInputs
from qonnx.transformation.infer_shapes import InferShapes
from qonnx.transformation.infer_datatypes import InferDataTypes
from qonnx.transformation.fold_constants import FoldConstants

model_for_sim = model_for_sim.transform(InferShapes())
model_for_sim = model_for_sim.transform(FoldConstants())
model_for_sim = model_for_sim.transform(GiveUniqueNodeNames())
model_for_sim = model_for_sim.transform(GiveReadableTensorNames())
model_for_sim = model_for_sim.transform(InferDataTypes())
model_for_sim = model_for_sim.transform(RemoveStaticGraphInputs())

verif_model_filename = model_dir + "/finn-brevitas-verification.onnx"
model_for_sim.save(verif_model_filename)

**Would the FINN compiler still work if we didn't do this?** The compilation step in the next notebook applies these transformations internally and would work fine, but we're going to use FINN's verification capabilities below and these require the tidy-up transformations.

Let's view our ready-to-go model after the transformations. Note that all intermediate tensors now have their shapes specified (indicated by numbers next to the arrows going between layers). Additionally, the datatype inference step has propagated quantization annotations to the outputs of `MultiThreshold` layers (expand by clicking the + next to the name of the tensor to see the quantization annotation) and the final output tensor.

In [6]:
#from finn.util.visualization import showInNetron

#showInNetron(verif_model_filename)

# 3. Load the Dataset and the Brevitas Model <a id="load_dataset"></a>

We'll use some example data from the quantized UNSW-NB15 dataset (from the previous notebook) to use as inputs for the verification. 

In [7]:
"""
import numpy as np
from torch.utils.data import TensorDataset

def get_preqnt_dataset(data_dir: str, train: bool):
    unsw_nb15_data = np.load(data_dir + "/unsw_nb15_binarized.npz")
    if train:
        partition = "train"
    else:
        partition = "test"
    part_data = unsw_nb15_data[partition].astype(np.float32)
    part_data = torch.from_numpy(part_data)
    part_data_in = part_data[:, :-1]
    part_data_out = part_data[:, -1]
    return TensorDataset(part_data_in, part_data_out)

n_verification_inputs = 100
test_quantized_dataset = get_preqnt_dataset(".", False)
input_tensor = test_quantized_dataset.tensors[0][:n_verification_inputs]
input_tensor.shape

train_quantized_dataset = get_preqnt_dataset(".", True)
test_quantized_dataset = get_preqnt_dataset(".", False)

print("Samples in each set: train = %d, test = %s" % (len(train_quantized_dataset), len(test_quantized_dataset))) 
print("Shape of one input sample: " +  str(train_quantized_dataset[0][0].shape))

"""

import numpy as np
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, models
import pandas as pd
from sklearn.model_selection import train_test_split
from PIL import Image

data_path = model_dir + "/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone"

# Prepare dataset
def load_dataset(data_path):
    images = []
    labels = []
    for subfolder in os.listdir(data_path):
        subfolder_path = os.path.join(data_path, subfolder)
        if not os.path.isdir(subfolder_path):
            continue
        for image_filename in os.listdir(subfolder_path):
            image_path = os.path.join(subfolder_path, image_filename)
            images.append(image_path)
            labels.append(subfolder)
    return pd.DataFrame({'image': images, 'label': labels})

# Define Custom Dataset class
class CustomDataset(Dataset):
    def __init__(self, dataframe, transform=None, class_indices=None):
        self.dataframe = dataframe
        self.transform = transform
        self.class_indices = class_indices

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        img_path = self.dataframe.iloc[idx]['image']
        image = Image.open(img_path).convert('RGB')
        label = self.class_indices[self.dataframe.iloc[idx]['label']]

        if self.transform:
            image = self.transform(image)

        return image, label

input_size = (3, 64, 64)

transform = transforms.Compose([
    transforms.Resize((input_size[1], input_size[2])),
    #transforms.RandomHorizontalFlip(),
    #transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

data = load_dataset(data_path)
train_df, dummy_df = train_test_split(data, train_size=0.01, shuffle=True, stratify=data['label'], random_state=123)

class_indices = {label: idx for idx, label in enumerate(train_df['label'].unique())}
train_quantized_dataset = CustomDataset(train_df, transform=transform, class_indices=class_indices)


Let's also bring up the MLP we trained in Brevitas from the previous notebook. We'll compare its outputs to what is generated by FINN.

In [8]:
"""
input_size = 593      
hidden1 = 64      
hidden2 = 64
hidden3 = 64
weight_bit_width = 2
act_bit_width = 2
num_classes = 1

from brevitas.nn import QuantLinear, QuantReLU
import torch.nn as nn

brevitas_model = nn.Sequential(
      QuantLinear(input_size, hidden1, bias=True, weight_bit_width=weight_bit_width),
      nn.BatchNorm1d(hidden1),
      nn.Dropout(0.5),
      QuantReLU(bit_width=act_bit_width),
      QuantLinear(hidden1, hidden2, bias=True, weight_bit_width=weight_bit_width),
      nn.BatchNorm1d(hidden2),
      nn.Dropout(0.5),
      QuantReLU(bit_width=act_bit_width),
      QuantLinear(hidden2, hidden3, bias=True, weight_bit_width=weight_bit_width),
      nn.BatchNorm1d(hidden3),
      nn.Dropout(0.5),
      QuantReLU(bit_width=act_bit_width),
      QuantLinear(hidden3, num_classes, bias=True, weight_bit_width=weight_bit_width)
)

# replace this with your trained network checkpoint if you're not
# using the pretrained weights
trained_state_dict = torch.load(model_dir + "/state_dict.pth")["models_state_dict"][0]

# Uncomment the following line if you previously chose to train the network yourself
#trained_state_dict = torch.load("state_dict_self-trained.pth")

brevitas_model.load_state_dict(trained_state_dict, strict=False)
"""

from brevitas.nn import QuantLinear, QuantReLU, QuantConv2d
import torch.nn as nn

input_size = (3, 64, 64)

class QuantMobileNetV2Model(nn.Module):
    def __init__(self, num_classes=4):
        super(QuantMobileNetV2Model, self).__init__()

        self.conv1 = QuantConv2d(3, 6, 5, bias=True, weight_bit_width=8, padding=2)
        self.lin2_2 = QuantLinear(int(6*input_size[1]*input_size[2]/4), 32, bias=True, weight_bit_width=8)
        
        self.lin1 = QuantLinear(input_size[0]*input_size[1]*input_size[2], 64, bias=True, weight_bit_width=8)
        self.bnorm1 = nn.BatchNorm1d(64)
        self.drop1 = nn.Dropout(0.5)
        self.relu1 = QuantReLU(bit_width=8)
        self.lin2 = QuantLinear(64, 32, bias=True, weight_bit_width=8)
        self.bnorm2 = nn.BatchNorm1d(32)
        self.drop2 = nn.Dropout(0.5)
        self.relu2 = QuantReLU(bit_width=8)
        self.lin3 = QuantLinear(32, 16, bias=True, weight_bit_width=8)
        self.bnorm3 = nn.BatchNorm1d(16)
        self.drop3 = nn.Dropout(0.5)
        self.relu3 = QuantReLU(bit_width=8)
        self.lin4 = QuantLinear(16, 4, bias=True, weight_bit_width=8)

    def forward(self, x):
        
        out = x.view(-1, input_size[0]*input_size[1]*input_size[2])
        out = self.lin1(out)
        out = self.bnorm1(out)
        out = self.drop1(out)
        out = self.relu1(out)
        out = self.lin2(out)

        #out = self.conv1(x)
        #out = self.relu1(out)
        #out = nn.functional.max_pool2d(out, 2)
        #out = out.view(-1, int(6*input_size[1]*input_size[2]/4))
        #out = self.lin2_2(out)
         
        out = self.bnorm2(out)
        #print(out.shape)
        out = self.drop2(out)
        #print(out.shape)
        out = self.relu2(out)
        out = self.lin3(out)
        out = self.bnorm3(out)
        #print(out.shape)
        out = self.drop3(out)
        #print(out.shape)
        out = self.relu3(out)
        out = self.lin4(out)
        #print(out.shape)

        return out

brevitas_model = QuantMobileNetV2Model(num_classes=4) #.to(device)

#trained_state_dict = torch.load(model_dir + "/state_dict.pth")["models_state_dict"][0]
trained_state_dict = torch.load("state_dict_self-trained.pth")
brevitas_model.load_state_dict(trained_state_dict, strict=False)

<All keys matched successfully>

In [9]:
def inference_with_brevitas(current_inp):
    brevitas_output = brevitas_model.forward(current_inp)
    # apply sigmoid + threshold
    # brevitas_output = torch.sigmoid(brevitas_output)
    
    #brevitas_output = (brevitas_output.detach().numpy() > 0.5) * 1
    brevitas_output = brevitas_output.detach().numpy()
    # convert output to bipolar
    #brevitas_output = 2*brevitas_output - 1
    return brevitas_output

# 4. Compare FINN & Brevitas execution <a id="compare_brevitas"></a>

Let's make helper functions to execute the same input with Brevitas and FINN. For FINN, we'll use the [`finn.core.onnx_exec`](https://finn.readthedocs.io/en/latest/source_code/finn.core.html#finn.core.onnx_exec.execute_onnx) function to execute the exported FINN-ONNX on the inputs. Note that this ONNX execution is for verification only; not for accelerated execution.

Recall that the quantized values from the dataset are 593-bit binary {0, 1} vectors whereas our exported model takes 600-bit bipolar {-1, +1} vectors, so we'll have to preprocess it a bit before we can use it for verifying the ONNX model.

In [10]:
import finn.core.onnx_exec as oxe

def inference_with_finn_onnx(current_inp):
    finnonnx_in_tensor_name = model_for_sim.graph.input[0].name
    finnonnx_model_in_shape = model_for_sim.get_tensor_shape(finnonnx_in_tensor_name)
    finnonnx_out_tensor_name = model_for_sim.graph.output[0].name
    # convert input to numpy for FINN
    current_inp = current_inp.detach().numpy()
    # add padding and re-scale to bipolar
    # current_inp = np.pad(current_inp, [(0, 0), (0, 7)])
    # current_inp = 2*current_inp-1
    # reshape to expected input (add 1 for batch dimension)
    current_inp = current_inp.reshape(finnonnx_model_in_shape)
    # create the input dictionary
    input_dict = {finnonnx_in_tensor_name : current_inp} 
    # run with FINN's execute_onnx
    output_dict = oxe.execute_onnx(model_for_sim, input_dict)
    #get the output tensor
    finn_output = output_dict[finnonnx_out_tensor_name] 
    return finn_output

Now we can call our inference helper functions for each input and compare the outputs.

In [11]:
import numpy as np
from tqdm import trange

verify_range = trange(len(train_quantized_dataset), desc="FINN execution", position=0, leave=True)
brevitas_model.eval()

ok = 0
nok = 0

"""
for i in verify_range:
    # run in Brevitas with PyTorch tensor
    current_inp = input_tensor[i].reshape((1, 3, 224, 224))
    brevitas_output = inference_with_brevitas(current_inp)
    finn_output = inference_with_finn_onnx(current_inp)
    # compare the outputs
    ok += 1 if finn_output == brevitas_output else 0
    nok += 1 if finn_output != brevitas_output else 0
    verify_range.set_description("ok %d nok %d" % (ok, nok))
    verify_range.refresh()
"""


for images, labels in train_quantized_dataset:
    # run in Brevitas with PyTorch tensor
    # print(images.shape)
    current_inp = images.reshape((1, input_size[0], input_size[1], input_size[2]))
    brevitas_output = inference_with_brevitas(current_inp)
    finn_output = inference_with_finn_onnx(current_inp)
    print(brevitas_output)
    print(finn_output)
    # compare the outputs
    ok += 1 if (finn_output == brevitas_output).all() else 0
    nok += 1 if (finn_output != brevitas_output).all() else 0
    verify_range.set_description("ok %d nok %d" % (ok, nok))
    verify_range.refresh()

FINN execution:   0%|                                   | 0/124 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:1255: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  return super(Tensor, self).rename(names)
ok 0 nok 0:   0%|                                       | 0/124 [00:02<?, ?it/s]

[[ 0.92643344 -1.10368     0.13520893 -0.46188062]]
[[ 0.92643344 -1.1036801   0.13520893 -0.46188068]]


ok 0 nok 0:   0%|                                       | 0/124 [00:04<?, ?it/s]

[[ 3.1102452  -0.40657514 -1.0091041  -4.312302  ]]
[[ 3.1102452 -0.4065752 -1.0091041 -4.3123016]]


ok 0 nok 0:   0%|                                       | 0/124 [00:06<?, ?it/s]

[[-2.6888947   1.8665361  -3.0737712  -0.13026436]]
[[-2.688895    1.8665361  -3.0737715  -0.13026439]]


ok 0 nok 0:   0%|                                       | 0/124 [00:08<?, ?it/s]

[[-3.2312062   0.05816138 -0.35250396  1.8546962 ]]
[[-3.2312062   0.05816138 -0.35250393  1.8546962 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:10<?, ?it/s]

[[ 2.6876714  -0.28340334 -0.98695695 -3.6922972 ]]
[[ 2.6876717  -0.28340343 -0.9869571  -3.6922975 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:12<?, ?it/s]

[[ 3.312413   1.361769  -2.6837668 -5.59921  ]]
[[ 3.3124127  1.3617687 -2.6837668 -5.59921  ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:14<?, ?it/s]

[[ 2.7670224 -0.7564302 -0.6960821 -3.5320554]]
[[ 2.7670224  -0.75643045 -0.69608206 -3.5320556 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:16<?, ?it/s]

[[ 1.1513404  -3.1617146   1.68516     0.17340146]]
[[ 1.1513404  -3.1617146   1.6851598   0.17340149]]


ok 0 nok 1:   0%|                                       | 0/124 [00:19<?, ?it/s]

[[ 0.1085255 -3.5775378  2.319376   1.0952947]]
[[ 0.10852557 -3.5775378   2.319376    1.0952948 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:21<?, ?it/s]

[[ 0.6835246  3.3522959 -4.8897257 -4.727059 ]]
[[ 0.6835246  3.3522956 -4.889726  -4.727059 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:23<?, ?it/s]

[[ 1.959892   -2.3872721   0.88963604 -1.3454014 ]]
[[ 1.959892  -2.3872721  0.8896361 -1.3454014]]


ok 0 nok 1:   0%|                                       | 0/124 [00:25<?, ?it/s]

[[-5.080559   1.1125827 -1.2112718  2.3997314]]
[[-5.080559   1.1125829 -1.2112718  2.3997316]]


ok 0 nok 1:   0%|                                       | 0/124 [00:27<?, ?it/s]

[[-1.0813849  2.8211176 -4.2720904 -2.6274536]]
[[-1.0813849  2.8211174 -4.2720904 -2.6274536]]


ok 0 nok 1:   0%|                                       | 0/124 [00:29<?, ?it/s]

[[ 2.7871563  1.8529162 -3.0423858 -5.0746636]]
[[ 2.787156   1.8529162 -3.042386  -5.0746636]]


ok 0 nok 1:   0%|                                       | 0/124 [00:31<?, ?it/s]

[[ 2.2320542 -0.9070789 -0.3747696 -2.6274536]]
[[ 2.2320542  -0.9070789  -0.37476954 -2.6274536 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:33<?, ?it/s]

[[ 2.282389   -0.6898703  -0.63579893 -2.7880507 ]]
[[ 2.282389   -0.68987036 -0.6357989  -2.788051  ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:35<?, ?it/s]

[[ 2.5801327  0.6240409 -1.7175789 -4.048193 ]]
[[ 2.5801332  0.6240409 -1.7175786 -4.0481925]]


ok 0 nok 1:   0%|                                       | 0/124 [00:37<?, ?it/s]

[[ 2.7318475  1.0376139 -2.1958172 -4.510087 ]]
[[ 2.7318473  1.0376139 -2.195817  -4.510087 ]]


ok 0 nok 1:   0%|                                       | 0/124 [00:39<?, ?it/s]

[[-4.6055183  1.1170833 -1.3916473  2.1018689]]
[[-4.605519   1.1170833 -1.3916473  2.1018689]]


ok 0 nok 1:   0%|                                       | 0/124 [00:42<?, ?it/s]

[[-1.5347518  2.8822296 -4.3146086 -2.3548176]]
[[-1.5347517  2.8822298 -4.3146086 -2.3548174]]


ok 0 nok 1:   0%|                                       | 0/124 [00:44<?, ?it/s]

[[-4.9021964  0.5474139 -0.6070194  2.5823572]]
[[-4.902197   0.547414  -0.6070194  2.5823574]]


ok 0 nok 1:   0%|                                       | 0/124 [00:46<?, ?it/s]

[[-6.04272     0.47884017 -0.3513196   3.275317  ]]
[[-6.04272     0.4788404  -0.35131952  3.275317  ]]


ok 0 nok 2:   0%|                                       | 0/124 [00:48<?, ?it/s]

[[ 3.2906208   0.62688357 -1.8984281  -5.1752152 ]]
[[ 3.290621   0.6268833 -1.8984283 -5.175215 ]]


ok 0 nok 2:   0%|                                       | 0/124 [00:50<?, ?it/s]

[[ 2.8959978  2.0085392 -3.2453828 -5.287017 ]]
[[ 2.8959975  2.008539  -3.2453825 -5.287017 ]]


ok 0 nok 2:   0%|                                       | 0/124 [00:52<?, ?it/s]

[[-5.3361406  1.2232006 -1.3411943  2.4803853]]
[[-5.3361406  1.2232006 -1.341194   2.4803853]]


ok 0 nok 3:   0%|                                       | 0/124 [00:54<?, ?it/s]

[[-2.6784728  -0.3173941  -0.01034693  1.7295109 ]]
[[-2.678473   -0.31739414 -0.01034693  1.7295108 ]]


ok 0 nok 3:   0%|                                       | 0/124 [00:56<?, ?it/s]

[[-3.3993828  -0.11735839 -0.15187603  2.034598  ]]
[[-3.3993833  -0.11735842 -0.15187603  2.034598  ]]


ok 0 nok 3:   0%|                                       | 0/124 [00:58<?, ?it/s]

[[ 0.9678855  0.5840102 -1.5080684 -1.7189435]]
[[ 0.9678855  0.5840102 -1.5080683 -1.7189434]]


ok 0 nok 3:   0%|                                       | 0/124 [01:00<?, ?it/s]

[[ 0.7111198  -2.472071    1.259033    0.35685632]]
[[ 0.7111198  -2.4720714   1.259033    0.35685635]]


ok 0 nok 3:   0%|                                       | 0/124 [01:02<?, ?it/s]

[[ 1.9781308  1.3249357 -2.3352144 -3.4486778]]
[[ 1.9781309  1.3249357 -2.3352144 -3.4486775]]


ok 0 nok 3:   0%|                                       | 0/124 [01:05<?, ?it/s]

[[-0.89248204  2.9882286  -4.45294    -2.9960215 ]]
[[-0.89248204  2.9882283  -4.45294    -2.9960215 ]]


ok 0 nok 3:   0%|                                       | 0/124 [01:07<?, ?it/s]

[[-4.5894117   0.40043682 -0.4962833   2.4781349 ]]
[[-4.5894117   0.40043676 -0.4962833   2.478135  ]]


ok 0 nok 3:   0%|                                       | 0/124 [01:09<?, ?it/s]

[[ 2.6574707  2.1339612 -3.3194041 -4.9887986]]
[[ 2.6574707  2.133961  -3.3194041 -4.9887986]]


ok 0 nok 3:   0%|                                       | 0/124 [01:11<?, ?it/s]

[[ 3.2098486  1.1655228 -2.4161048 -5.322784 ]]
[[ 3.2098486  1.165523  -2.416105  -5.322784 ]]


ok 0 nok 3:   0%|                                       | 0/124 [01:13<?, ?it/s]

[[ 2.69383   -0.309222  -0.9546244 -3.6880336]]
[[ 2.69383    -0.30922207 -0.9546244  -3.6880338 ]]


ok 0 nok 3:   0%|                                       | 0/124 [01:15<?, ?it/s]

[[-5.073808   0.8562909 -0.9232393  2.5212452]]
[[-5.073808    0.85629064 -0.92323923  2.5212452 ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:17<?, ?it/s]

[[-4.311209   -0.33812016  0.25020874  2.6855137 ]]
[[-4.3112097  -0.33812004  0.2502087   2.6855135 ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:19<?, ?it/s]

[[-3.0083125   0.46000928 -0.7607472   1.5432137 ]]
[[-3.0083125   0.46000928 -0.76074725  1.5432136 ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:21<?, ?it/s]

[[ 2.3851898  1.4187357 -2.5217485 -4.134768 ]]
[[ 2.38519    1.4187355 -2.5217485 -4.134768 ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:23<?, ?it/s]

[[ 2.5588148  2.1282763 -3.3519735 -4.8867087]]
[[ 2.558815   2.128276  -3.3519733 -4.8867087]]


ok 0 nok 4:   0%|                                       | 0/124 [01:26<?, ?it/s]

[[-3.8024151   0.13467002 -0.33746278  2.14794   ]]
[[-3.8024151   0.13467008 -0.33746278  2.14794   ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:28<?, ?it/s]

[[-0.33809057  2.6949847  -4.0746603  -3.095625  ]]
[[-0.33809063  2.6949847  -4.0746603  -3.0956247 ]]


ok 0 nok 4:   0%|                                       | 0/124 [01:30<?, ?it/s]

[[ 0.6532053  1.0251782 -2.0292983 -1.9394683]]
[[ 0.6532053  1.0251784 -2.0292983 -1.9394683]]


KeyboardInterrupt: 

In [ ]:
try:
    assert ok == n_verification_inputs
    print("Verification succeeded. Brevitas and FINN-ONNX execution outputs are identical")
except AssertionError:
    assert False, "Verification failed. Brevitas and FINN-ONNX execution outputs are NOT identical"

This concludes our second notebook. In the next one, we'll take the ONNX model we just verified all the way down to FPGA hardware with the FINN compiler.